### ISSUE TITLE
bug: Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/snacks.nvim/lua/snacks/util/init.lua:207: Invalid window id: 1002

### ISSUE THREAD

**Issue by huyhoang8398** [folke/snacks.nvim#1968]
### Did you check docs and existing issues?

- [x] I have read all the snacks.nvim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of snacks.nvim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.11.1

### Operating system/version

Ubuntu 24.04

### Describe the bug

```
Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/snacks.nvim/lua/snacks/util/init.lua:207: Invalid window id: 1002
stack traceback:
        [C]: in function 'nvim__redraw'
        ...cal/share/nvim/lazy/snacks.nvim/lua/snacks/util/init.lua:207: in function 'redraw_range'
        ....local/share/nvim/lazy/snacks.nvim/lua/snacks/indent.lua:453: in function 'cb'
        .../.local/share/nvim/lazy/snacks.nvim/lua/snacks/scope.lua:610: in function 'cb'
        .../.local/share/nvim/lazy/snacks.nvim/lua/snacks/scope.lua:562: in function 'get'
        .../.local/share/nvim/lazy/snacks.nvim/lua/snacks/scope.lua:500: in function 'cb'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:478: in function '_run_async_callbacks'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:534: in function <...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:513>
```

I have this weird error that i dont quite understand, see the step to reproduce

### Steps To Reproduce

1. Install Snacks.nvim
2. Install Harpoon.nvim
3. Open the project, add a file to Harpoon list ( ie: gitlab-ci.yml file )
4. Close nvim
5. Re-open NVIM and harpoon menu
6. Chose the file that previously added
7. See the error

### Expected Behavior

No error

### Checkhealth Treesitter
```

==============================================================================
nvim-treesitter:                     require("nvim-treesitter.health").check()

Installation ~
- ✅ OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- ✅ OK `node` found v22.14.0 (only needed for :TSInstallFromGrammar)
- ✅ OK `git` executable found.
- ✅ OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
- ✅ OK Neovim was compiled with tree-sitter runtime ABI version 15 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.11.0-26-generic",
  sysname = "Linux",
  version = "#26~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr 17 19:20:47 UTC 2"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - git_rebase          ✓ . . . ✓
  - gitignore           ✓ . . . ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

```

==============================================================================
snacks:                                       require("snacks.health").check()

Snacks ~
- ✅ OK setup called
- ⚠️ WARNING `snacks.nvim` should have a priority of 1000 or higher. Add `priority=1000` to the plugin spec

Snacks.bigfile ~
- ⚠️ WARNING setup {disabled}

Snacks.dashboard ~
- ⚠️ WARNING setup {disabled}

Snacks.explorer ~
- ✅ OK setup {enabled}

Snacks.image ~
- ✅ OK setup {enabled}
- ✅ OK 'kitty' `kitty 0.42.1 created by Kovid Goyal`
- ✅ OK 'ghostty' `Ghostty 1.1.3`
- ❌ ERROR None of the tools found: 'magick', 'convert'
- ❌ ERROR `magick` is required to convert images. Only PNG files will be displayed.
- ✅ OK `kitty` detected and supported
- ✅ OK `kitty` supports unicode placeholders
- ✅ OK Inline images are available
- ✅ OK `tmux` detected and supported
- ✅ OK Terminal Dimensions:
  - {size}: `2506` x `1280` pixels
  - {scale}: `1.75`
  - {cell}: `14` x `32` pixels
- ✅ OK Available Treesitter languages:
    `javascript`, `markdown_inline`, `markdown`
- ⚠️ WARNING Missing Treesitter languages:
    `css`, `html`, `latex`, `norg`, `scss`, `svelte`, `tsx`, `typst`, `vue`
- ⚠️ WARNING Image rendering in docs with missing treesitter parsers won't work
- ✅ OK 'gs' `10.02.1`
- ✅ OK PDF files are supported
- ❌ ERROR None of the tools found: 'tectonic', 'pdflatex'
- ⚠️ WARNING `tectonic` or `pdflatex` is required to render LaTeX math expressions
- ❌ ERROR Tool not found: 'mmdc'
- ⚠️ WARNING `mmdc` is required to render Mermaid diagrams
- ✅ OK your terminal supports the kitty graphics protocol

Snacks.input ~
- ✅ OK setup {enabled}
- ✅ OK `vim.ui.input` is set to `Snacks.input`

Snacks.lazygit ~
- ❌ ERROR {lazygit} not installed

Snacks.notifier ~
- ⚠️ WARNING setup {disabled}
- ❌ ERROR is not ready

Snacks.picker ~
- ✅ OK setup {enabled}
- ✅ OK `vim.ui.select` is set to `Snacks.picker.select`
- ✅ OK Available Treesitter languages:
    `regex`
- ✅ OK 'git' `git version 2.43.0`
- ✅ OK 'rg' `ripgrep 14.1.0`
- ✅ OK `Snacks.picker.grep()` is available
- ✅ OK 'fdfind' `fdfind 9.0.0`
- ✅ OK `Snacks.picker.files()` is available
- ✅ OK `Snacks.picker.explorer()` is available
- ✅ OK `SQLite3` is available

Snacks.quickfile ~
- ⚠️ WARNING setup {disabled}

Snacks.scope ~
- ⚠️ WARNING setup {disabled}

Snacks.scroll ~
- ⚠️ WARNING setup {disabled}

Snacks.statuscolumn ~
- ⚠️ WARNING setup {disabled}

Snacks.terminal ~
- ✅ OK shell configured
  - `vim.o.shell`: /usr/bin/zsh
  - `parsed`: { "/usr/bin/zsh" }

Snacks.toggle ~
- ⚠️ WARNING {which-key} is not installed

Snacks.words ~
- ⚠️ WARNING setup {disabled}

```

**Comment by drowning-cat** [comment]
What version of Harpoon do you use? I expect you to use:
```lua
{
    "ThePrimeagen/harpoon",
    branch = "harpoon2",
    dependencies = { "nvim-lua/plenary.nvim" }
}
```

**Comment by huyhoang8398** [comment]
> What version of Harpoon do you use? I expect you to use:
> 
> {
>     "ThePrimeagen/harpoon",
>     branch = "harpoon2",
>     dependencies = { "nvim-lua/plenary.nvim" }
> }

yes it's correct, 
```
    ● harpoon 6.31ms  start
        dir    /home/kn/.local/share/nvim/lazy/harpoon
        url    https://github.com/ThePrimeagen/harpoon
        branch harpoon2
        commit ed1f853
        readme README.md
```

**Comment by huyhoang8398** [comment]
> What version of Harpoon do you use? I expect you to use:
> 
> {
>     "ThePrimeagen/harpoon",
>     branch = "harpoon2",
>     dependencies = { "nvim-lua/plenary.nvim" }
> }

it looks like it only happend to yaml

**Comment by drowning-cat** [comment]
The issue is related to (not duplicate):
  - https://github.com/folke/snacks.nvim/issues/1737
  - https://github.com/folke/snacks.nvim/discussions/1937#discussion-8398426
  - https://github.com/folke/snacks.nvim/pull/1943

**Comment by elijahworkz** [comment]
> > What version of Harpoon do you use? I expect you to use:
> > {
> > "ThePrimeagen/harpoon",
> > branch = "harpoon2",
> > dependencies = { "nvim-lua/plenary.nvim" }
> > }
> 
> it looks like it only happend to yaml

It happens for me as well on any file that is opened from harpoon - js, php etc.

**Comment by Kyren223** [comment]
It happens to me aswell.
I also have harpoon but it happens anytime I switch to a file for the first time (even with the snacks picker).

I also have auto-session.nvim, so what happens for me is:
Open nvim for the first time (no session)
See the snacks dashboard
Open a file (tested by harpooning or snacks picker)
Get this error and for some reason the background is also pure black (but the rest of my theme on text applies fine, probably bcz it's delayed due to syntax highlighting or something)

And then I fix it by:
Closing nvim and reopening it
I then see the stock nvim dashboard (not the snacks one)
Then harpooning/using snacks picker works fine.

This is really annoying hopefully this gets fixed soon (it's been happening to me for about a month now, probably ever since I installed snacks, I updated 30s ago my nvim plugins hoping this will get fixed and it hasn't yet)

**Comment by asiryk** [comment]
Opened the PR #1996. Fix works for me. Please check if it works for you:
https://github.com/asiryk/snacks.nvim

**Comment by Kyren223** [comment]
@asiryk it didn't fix it for me, here's my exact error:

When using harpoon
```
E5108: Error executing lua: ...en/.local/share/nvim/lazy/harpoon/lua/harpoon/config.lua:131: BufWinEnter Autocommands for "*": Vim(append):Error executing lua callback: ...en/.local/share/nvim/lazy/snacks.nvim/lua/snacks/win.lua:887: Invalid buffer id: 2
stack traceback:
	[C]: in function 'nvim_win_set_buf'
	...en/.local/share/nvim/lazy/snacks.nvim/lua/snacks/win.lua:887: in function <...en/.local/share/nvim/lazy/snacks.nvim/lua/snacks/win.lua:847>
	[C]: in function 'nvim_set_current_buf'
	...en/.local/share/nvim/lazy/harpoon/lua/harpoon/config.lua:131: in function 'select'
	...yren/.local/share/nvim/lazy/harpoon/lua/harpoon/list.lua:295: in function 'select'
	/home/kyren/.config/nvim/lua/plugins/harpoon.lua:35: in function </home/kyren/.config/nvim/lua/plugins/harpoon.lua:34>
stack traceback:
	[C]: in function 'nvim_set_current_buf'
	...en/.local/share/nvim/lazy/harpoon/lua/harpoon/config.lua:131: in function 'select'
	...yren/.local/share/nvim/lazy/harpoon/lua/harpoon/list.lua:295: in function 'select'
	/home/kyren/.config/nvim/lua/plugins/harpoon.lua:35: in function </home/kyren/.config/nvim/lua/plugins/harpoon.lua:34>
```

When using snacks picker
```
Error executing vim.schedule lua callback: vim/_editor.lua:0: nvim_exec2()[1]..BufWinEnter Autocommands for "*": Vim(append):Error executing lua callback: ...en/.local/share/nvim/lazy/snacks.nvim/lua/snacks/win.lua:887: Invalid buffer id: 2
stack traceback:
	[C]: in function 'nvim_win_set_buf'
	...en/.local/share/nvim/lazy/snacks.nvim/lua/snacks/win.lua:887: in function <...en/.local/share/nvim/lazy/snacks.nvim/lua/snacks/win.lua:847>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/actions.lua:115: in function 'jump'
	...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/actions.lua:36: in function <...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/actions.lua:35>
stack traceback:
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/actions.lua:115: in function 'jump'
	...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/actions.lua:36: in function <...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/actions.lua:35>
```

My nvim:
NVIM v0.11.2
Build type: Release
LuaJIT 2.1.1741730670
Run "nvim -V1 -v" for more info

And this is my auto-session code which calls into the dashboard
I only have the dashboard if A) it's in home/root where there is never a session, or B) there is no session yet (first time open).

In the case where there is no session like in $HOME, it always errors (starts the dashboard, and when using the snacks picker on a file it gives the error, due to no session it doesn't go directly to the file but rather the dashboard which causes it again).

```
return {
    'rmagatti/auto-session',
    lazy = false,
    opts = {
        suppressed_dirs = { '~/', '/' },
        session_lens = { load_on_setup = false },
        no_restore_cmds = {
            function()
                if vim.fn.argc() == 0 then
                    Snacks.dashboard()
                    -- vim.cmd('Alpha')
                end
            end,
        },
    },
    keys = {
        { '<C-s>', '<cmd>SessionSearch<cr>', desc = '[S]ession Manager' },
    },
}
```

Hopefully this helps you fix it.
If for you it works, what NVIM version are you using?

**Comment by asiryk** [comment]
@Kyren223 I also use v0.11.2

NVIM v0.11.2
Build type: Release
LuaJIT 2.1.1748459687

Regarding Harpoon, I want to note that I'm using harpoon2 (as Prime rewrote it from scratch).
Seems like you have similar but not the same issue. I fixed `Invalid window id: 2`, but you have `Invalid buffer id: 2`. I wonder where these invalid ids are coming from...

**Comment by Kyren223** [comment]
I also use harpoon2, you can see my dotfiles at kyren223/dotfiles on github, if you want to see my exact snacks/harpoon config

**Comment by huyhoang8398** [comment]
any update for this?

**Comment by Kyren223** [comment]
It still happens to me, I am not aware of any new fix other than the one that I tested and doesn't work.

**Comment by ollien** [comment]
I've faced this issue when switching to files from nvim-tree as my main window. It seems to only happen when the file has merge conflicts, which is an interesting detail.

**Comment by euoia** [comment]
I am also seeing this intermittently, here's the stack:
```
Error executing vim.schedule lua callback: vim/_editor.lua:0: nvim_exec2()[1]..BufWinEnter Autocommands for "*": Vim(append):Error executing lua callback: ...rd/.local/share/nvim/lazy/snacks.nvim/lua/snacks/win.lua:887: Invalid buffer id: 17
stack traceback:
        [C]: in function 'nvim_win_set_buf'
        ...rd/.local/share/nvim/lazy/snacks.nvim/lua/snacks/win.lua:887: in function <...rd/.local/share/nvim/lazy/snacks.nvim/lua/snacks/win.lua:847>
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/actions.lua:115: in function 'jump'
        ...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/actions.lua:36: in function <...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/actions.lua:35>
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/actions.lua:115: in function 'jump'
        ...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/actions.lua:36: in function <...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/actions.lua:35>
```

**Comment by folke** [comment]
@euoia you're not using the latest version of snacks

**Comment by euoia** [comment]
@folke hmm
```
jamespickard@James-2021 ~/.l/s/n/l/snacks.nvim ((stable))> git log -1 --oneline
da230e3 (HEAD, tag: v2.23.0, tag: stable) chore(main): release 2.23.0 (#1434)
```

**Comment by folke** [comment]
not the latest HEAD I meant
