### ISSUE TITLE
bug: Prompt hides first row of picker results

### ISSUE THREAD

**Issue by oysandvik94** [folke/snacks.nvim#2626]
### Did you check docs and existing issues?

- [x] I have read all the snacks.nvim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of snacks.nvim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.12.0-dev-1831+gdf849f6541

### Operating system/version

Arch linux

### Describe the bug

<img width="1383" height="122" alt="Image" src="https://github.com/user-attachments/assets/62abea3d-97f4-4a0e-a4b3-976d776711d3" />

Prompt ends up on 2 lines, and hides the first result.
I get this with newest version of neovim, and newest version of snacks.
I also get the issue using the config from the readme:
https://github.com/folke/snacks.nvim?tab=readme-ov-file#-usage

### Steps To Reproduce

1. Install latest neovim version
2. Install latest snacks version
3. Open any picker

### Expected Behavior

First row should be visible in results

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Are you sure you're actually using latest Neovim? This used to be a Neovim issue with a past version and got fixed via another update. What does `:=vim.version().build` print out?

PS: Related issue #2561 that got fixed upstream in Neovim

**Comment by oysandvik94** [comment]
I get gdf849f6541. Pulled again and build and am on g99e8b61376 with same issue. 
Thanks for the link to the other issue. Looks similar, but also different. Possible there's some config interferring on my end, I'll try a minimal reproduction.

**Comment by oysandvik94** [comment]
Yes, minimal config works, so I have to hunt through my config hehe.
Sorry for not checking first
I'll update here if I find anything, in case anyone runs in to similar issues.

**Comment by oysandvik94** [comment]
Dont know why I didnt spot it, but it was my custom statusline.

**Comment by rohrsben** [comment]
Hello! I also still have this issue and use a custom statusline. Could you share what you actually had to do to fix this? I'm not seeing the relation unfortunately haha

**Comment by oysandvik94** [comment]
@rohrsben 
```lua
vim.api.nvim_create_autocmd({ "WinEnter", "BufEnter" }, {
  group = group,
  desc = "Activate statusline on focus",
  callback = function()
    if vim.bo.filetype == "snacks_picker_input" then
      return
    end
    vim.opt_local.statusline = "%!v:lua.Statusline.active()"
  end,
})
```

I just ignored the snacks input filetype from where I activate the statusline
