### ISSUE TITLE
feature: [explorer]Improve the performance of cursor jump

### ISSUE THREAD

**Issue by xian-wen** [folke/snacks.nvim#869]
### Did you check the docs?

- [x] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

Hi, is it possible to improve the performance of the cursor jump in Snacks.explorer? Currently, it is a little bit sluggish, as you can see in the recording of the comparison between neo-tree and Snacks.explorer.
neo-tree:
![Image](https://github.com/user-attachments/assets/79bf7f07-6436-4ad3-9b22-416f1d9f40b0)
Snacks.explorer:
![Image](https://github.com/user-attachments/assets/f7022eb8-90a0-46a1-94cb-210549aae753)

### Describe the solution you'd like

Just make the cursor jump a little bit more smoother.

### Describe alternatives you've considered

Borrow the solution from neo-tree?

**Comment by folke** [comment]
That's not normal. It seems to be the git status command that is slow on your machine for some reason. Any ideas?

**Comment by folke** [comment]
Disable git status to test

**Comment by xian-wen** [comment]
Below is the time of `git status`, a little bit too long:
![Image](https://github.com/user-attachments/assets/222a42f0-bd20-43a4-848e-6a29084970c0)

**Comment by xian-wen** [comment]
So is it possible to not always run the `git status` command every time the keymap is triggered?

**Comment by xian-wen** [comment]
I will make a recording after disabling the `git_status`, which improves a lot, but still feels jumpy.

**Comment by folke** [comment]
That is **extremely** slow.
The same command for me runs in `5ms` so `1000x` faster than in your case.

What about the `fd` command?

There really must be something wrongly configured somewhere on your system.

I will however change it so that slow git commands don't prevent navigating the list.

**Comment by xian-wen** [comment]
Hi, below is the recording with `git_status = false`:
![Image](https://github.com/user-attachments/assets/e0a9776f-39a1-48a6-9b28-ba6f5c7b39b9)

**Comment by xian-wen** [comment]
It is not slow, but a little bit jumpy?

**Comment by xian-wen** [comment]
> That is extremely slow.
> The same command for me runs in 5ms so 1000x faster than in your case.
This is just an academic docker environment, Ubuntu 22.04. I think there is no problem for `fd` since Snacks.picker runs extremely fast.

**Comment by xian-wen** [comment]
Below is the recording of Snacks.picker, at least it is better than `telescope` and not slower than `fzf-lua`:
![Image](https://github.com/user-attachments/assets/cf2f8856-9b54-4b5b-91d1-2df72f8ed0b3)

**Comment by folke** [comment]
I just changed it so that git status no longer blocks anything.
But that of course won't fix your 5s execution time. It will just make sure you will be able to use the explorer
without waiting till it finished. 

Closing.

**Comment by xian-wen** [comment]
I find that neo-tree also displays the icons asynchronously when opening the first time, but when running the second, third, and so forth, time, the icons are displayed instantly. Maybe it uses some cache trick.

**Comment by folke** [comment]
you mean the git icons? So does the snacks picker. Did you update?

**Comment by xian-wen** [comment]
Yes, I have updated to the latest version of Snacks. I mean the git icons displayed in Snacks.explorer **each** time just like they displayed in neo-tree the **first** time. When they displayed the following time in neo-tree, I cannot see any delays.

**Comment by folke** [comment]
ok, you probably mean the directory status symbols.

**Comment by folke** [comment]
Just changed that as well. You should no longer see the delays for git status.

**Comment by xian-wen** [comment]
Below is the recording of the comparison between neo-tree and Snacks.explorer:
neo-tree:
![Image](https://github.com/user-attachments/assets/50a9bae9-c0ed-4b82-bad5-785d3fe87d09)
Snacks.explorer:
![Image](https://github.com/user-attachments/assets/01c999b2-9848-41f0-891e-2e52ce16dc2c)
As we can see, neo-tree also takes some time to display the icons the first time, but later, it displays extremely fast.

**Comment by folke** [comment]
ok, now I understand what you mean.
I don't keep the git status cache in betwen opening the explorer. Will chaneg

**Comment by folke** [comment]
And I also had pushed a 1 second sleep for testing, which didn't help :)

**Comment by folke** [comment]
try again

**Comment by xian-wen** [comment]
Awesome! Thank you so much.
![Image](https://github.com/user-attachments/assets/18f2a601-6f5b-4d16-974d-8e6d71b9503d)

**Comment by xian-wen** [comment]
Hi, folke, sorry to bother you once again. I just want Snacks.explorer to be better. Is it possible to improve the user experience when closing and opening a node? Currently, I could clearly see something like a refresh when closing and opening, which does not exist in neo-tree, as you can see in the recordings shown below:
neo-tree:
![Image](https://github.com/user-attachments/assets/1f818cff-c55f-466b-a81e-bac3ff04fa81)
Snacks.explorer:
![Image](https://github.com/user-attachments/assets/6340d389-a8f6-4066-907b-5c0d4a3e017f)

**Comment by folke** [comment]
This is getting a bit annoying tbh. On my laptop there's literally no visible delay.

I can indeed change it, but seriously, just fix your computer...

**Comment by xian-wen** [comment]
Yeah, this is indeed annoying, sorry once again. This problem does not exist on my WSL. On WSL, everything feels smooth and fast. And I also cannot see any visible delay. It just happens on a docker environment, which might also be used by other people.

**Comment by folke** [comment]
Allright, just added an additional caching layer.
When opening/closing directories already in the cache, the cache will be used.

If you do any operations like opening a directory not yet in the cache, saving a file, closing a terminal, then the cache will be invalidated.

**Comment by xian-wen** [comment]
Thank you so much. I've just tested it. Everything feels cool.

**Comment by xian-wen** [comment]
> When opening/closing directories already in the cache, the cache will be used.
> If you do any operations like opening a directory not yet in the cache, saving a file, closing a terminal, then the cache will be invalidated.

Hi, folke, if you have time, could you please add all of the visible directories into cache when opening explorer the first time, so that when opening any visible directory, no visible delay can be seen? Also, after opening any visible directory, adding all of its visible subdirectories into cache. In this case, I think we can not see any delays when opening any visible directory. Currently, seems the directories are added into cache on demand.
neo-tree:
![Image](https://github.com/user-attachments/assets/e1e4d166-9013-47f7-8332-a57913073a1e)
explorer:
![Image](https://github.com/user-attachments/assets/63b13cac-28d0-479a-bb54-03269938089b)

**Comment by patrick-5546** [comment]
This caching would be helpful on my work computer where the codebase is on a network attached storage device

**Comment by folke** [comment]
I'm rewriting the explorer as we speak to no longer use `fd` for just the exploring part.

**Comment by folke** [comment]
Just pushed all the changes. Let me know how it behaves on your (slower) machine.

**Comment by xian-wen** [comment]
I got an error when first opening explorer:
```lua
                     Error executing vim.schedule lua callback: ...lazyvim/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:611: attempt to index field 'picker' (a nil value)
stack traceback:
	...lazyvim/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:611: in function <...lazyvim/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:610>
```

**Comment by folke** [comment]
nm, added an extra nil check. weird that you get that though

**Comment by xian-wen** [comment]
I just press `<Leader>e` again and again, to reproduce it:

![Image](https://github.com/user-attachments/assets/5e9a9a05-0333-414e-a185-58c66d15e647)

**Comment by xian-wen** [comment]
Sometimes I got this error:
![Image](https://github.com/user-attachments/assets/0b6e91d3-dbbb-41c5-acaf-049034197d69)

**Comment by xian-wen** [comment]
In LazyVim, when I press `<Leader>e` the first time, the cursor does not focus on the file. In the following time, it is focused correctly.

![Image](https://github.com/user-attachments/assets/98b62df4-fe3d-4407-b4dc-17313d0d3473)

**Comment by folke** [comment]
That was probably related to those errors. Just fixed those.

**Comment by xian-wen** [comment]
Now the explorer does not display the complete tree, each time displays two or three more folders:
![Image](https://github.com/user-attachments/assets/4f90f4d9-a8de-41cd-b509-82fa875b948d)

**Comment by xian-wen** [comment]
Another bug: when `<Leader>E` is pressed, neovim freezes, and the explorer cannot be opened.

**Comment by xian-wen** [comment]
Just open LazyVim, and press `<Leader>E` or running `:lua Snacks.picker.explorer()`, nothing happens, it hangs like goes into a infinite loop.

**Comment by xian-wen** [comment]
The problem also exists on my fast WSL.

**Comment by folke** [comment]
it doesn't for me, so that's why I ask to reproduce it.

**Comment by folke** [comment]
Are you in a special directory? symlinks?

**Comment by xian-wen** [comment]
I just updated to the latest version of Snacks, and now both `<Leader>e` and `<Leader>E` are frozen.

**Comment by xian-wen** [comment]
I have `~/.config/nvim/` symlink to `~/.dotfiles/.config/nvim/`, does this matter?

**Comment by xian-wen** [comment]
When I run `lazyvim` in `~`, then press `n` to create a new file, then press `<Leader>e`, neovim is frozen. The same as `<Leader>E`.
![Image](https://github.com/user-attachments/assets/7addc973-a2e6-4847-8cef-716b3a72f7ba)

**Comment by folke** [comment]
Still can't reproduce this. Would be great if you could see what the minimal required directory structure is to trigger this.

Btw, I also just added link targets to explorer.

**Comment by xian-wen** [comment]
I just updated to the latest version of Snacks and LazyVim. Then run lazyvim in home directory (which has no visible files, all are dotfiles) on my WSL, `<Leader>e` and `<Leader>E` works, but `<Leader>E` with only 1 root entry is clearly slower than `<Leader>e`. 
![Image](https://github.com/user-attachments/assets/67484981-707c-4ee9-a7a7-222388a45520)

**Comment by xian-wen** [comment]
When you walk the tree, do you follow the symlink? I remember when I use `picker.files` on the home directory on my docker, with `f` toggled on, there are more than 1 million files, with `h` and `i` toggled on, there are about 80,000 files. And `telescope` totally cannot be used.

**Comment by folke** [comment]
oh, that might explain it. You probably have a recursive symlink somewhere?

**Comment by folke** [comment]
So again. You open nvim in your home diredctory.
What is the path of that file you have open?
In your screencast Neovim does not seem to hang?
What are the circumstances to make it hang?

If you open Neovim without a file and then do `leader-E`. Does that work?

**Comment by folke** [comment]
Visible/not visible files is all the same.
I need to process them anyway. Visibility just matters for showing the explorer.

Even with a recursive symlink, I don't really see how the explorer could get in a loop.

**Comment by folke** [comment]
leader-e will open the explorer in the root dir of the file you have open.
So in your case, the directory containing the session files.

leader-E will open your home directory.

**Comment by folke** [comment]
How may files are in your `~` directory? so top-level?

**Comment by folke** [comment]
Can you set `opts.sources.explorer.watch = false` and see if that fixes it?

**Comment by folke** [comment]
oof, for sure this is the issue.
I'm using Neovim's file watcher, but if you're on linux without inotify, it will recursively descend all directories and add watches to every directory sepeartly for 100 levels deep.

Will disable that.

**Comment by folke** [comment]
Just disabled it. Can you try again?

**Comment by xian-wen** [comment]
Hold a sec, let me have a try.

**Comment by xian-wen** [comment]
Yes, fixed. It's fast now. Thank you so much. BTW, could the marker in front of `code` dir be changed since that is the only folder.
![Image](https://github.com/user-attachments/assets/944fdd5c-088b-4024-84b6-0204f116f631)

**Comment by folke** [comment]
Is there a hidden or ignored file in there?

**Comment by xian-wen** [comment]
Just one `code` directory, all others are dotfiles, which is shown when `h` is toggled on.
![Image](https://github.com/user-attachments/assets/b7cd0b82-e25e-4843-a26a-34254bacfff0)

**Comment by folke** [comment]
fixed

**Comment by xian-wen** [comment]
Looks pretty beautiful. Thank you so much. I think my dream file explorer has been born. I have been sitting in front of my computer and refreshing the Snacks repo every few minutes. I am so excited and appreciated for what you have done. Have a good night. On my timezone, it is 4:15 now.🤣

**Comment by folke** [comment]
Thank you and get some sleep! :)

**Comment by xian-wen** [comment]
Hi, when `watch` is disabled, does this mean we can no longer track the file status? Since there is no git status icon when a file has changed.
![Image](https://github.com/user-attachments/assets/31005dc9-2e53-41c1-8e1f-21bfbbefcdd1)

**Comment by xian-wen** [comment]
Also, when `explorer` is opened, the content in the buffer has been changed to the top view. After closing, the content is back. As you can see in the above recording.

**Comment by folke** [comment]
When the file watcher is disabled, only buffer writes and lazygit terminal closes will result in a git refresh.
On linux, you can install inotify-tools. That will be used when available and doesn't have the associated issues like you experienced before.

I can't reproduce that issues when the explorer opened. But I'm also not sure I fully understand what you mean.

**Comment by xian-wen** [comment]
I mean before `<Leader>e` is pressed, the cursor is on Line 86, while after the explorer is opened, the visible range in the right window is [1, 31], i.e., the first 31 lines are shown.

**Comment by folke** [comment]
Did you enable the main preview for explorer?

**Comment by folke** [comment]
Just tried with the minimal repro and also can't reproduce this there

**Comment by xian-wen** [comment]
I think the problem comes from the preview, when I have
```lua
layout = { enabled = false, preview = "main" }
```
removed,
there is no such issue.

**Comment by xian-wen** [comment]
Sorry, my bad. The config should be:
```lua
            layout = {
              preview = {
                enabled = false,
                main = true,
              },
            },
```

**Comment by xian-wen** [comment]
I just tested LazyVim in both WSL and docker, the problem still exists when toggle in "main" is set, and disappears when this is unset.

**Comment by xian-wen** [comment]
I find the problem, `enabled = false` seems does not work. When the explorer is opened, with the above config, preview is toggled on by default, so all files are in preview state, thus only the top view is shown. When I press `P`, the preview is toggled off, and the cursor  line is back.

**Comment by folke** [comment]
fixed

**Comment by xian-wen** [comment]
I have tested. Seems git status icons are also displayed without `inotify-tools` installed.

**Comment by xian-wen** [comment]
Awesome! Thank you so much.

**Comment by xian-wen** [comment]
> On linux, you can install inotify-tools. That will be used when available and doesn't have the associated issues like you experienced before.

I have `inotify-tools` installed, and `inotifywait` is executable, however, git signs are still not shown, sign...
![Image](https://github.com/user-attachments/assets/ff6f4293-b347-4d38-afa6-5f799bb23e99)

**Comment by folke** [comment]
You no longer need inotity-tools.

I've changed the implementation since to no longer use NEovim's file watcher implementation,
since it's terrible for performance.

My new implementation works on all platforms, without any additional files needed.

**Comment by xian-wen** [comment]
I have uninstalled `inotify-tools`. There are still no git signs displayed when a file has changed.

**Comment by folke** [comment]
Can you check again?

**Comment by xian-wen** [comment]
I just updated and tested with LazyVim, nothing has changed.

**Comment by folke** [comment]
This is really annoying since I can't reproduce it.
IS there anything special about the directory or files you're doing this with?

Start with opening neovim from an actual project diretcory.
open a file from that project
see if it then works.

There's nothing for me to fix if I can't reproduce it.

**Comment by xian-wen** [comment]
I just run `lazyvim` in `.dofiles` on WSL, then press `f` to find the file `./.config/lazyvim/config/options.lua`, then add an option, no matter I updated the file or not, git status icons are not updated in explorer.
![Image](https://github.com/user-attachments/assets/7e503bb0-c785-4f27-a056-58e90698ce12)

**Comment by folke** [comment]
Do you wait long enough? That git status command on your machine took over 5 seconds

**Comment by folke** [comment]
ok, I can reproduce it in the exact same way indeed.

**Comment by folke** [comment]
If you'd keep the explorer open it would update properly.

**Comment by folke** [comment]
ok, check again.

**Comment by xian-wen** [comment]
Tested, OK! Thank you so much.
